### PR TITLE
Added command to retrieve the path of a project

### PR DESCRIPTION
**Pull request by ZakariaTalhami**
Solves #7 

Added a comment to get the path of a project, returning it to the terminal

`pm {getpath|path} [projectName]`

### CODE REVIEW

**Comment by saurabhdaware** [comment]
Seems great! working in linux. I will check in windows in some time. 
By the way, how did you solve that color issue? Even I was getting color issues as well when I tried.

**Comment by ZakariaTalhami** [comment]
I wasnt able to solve the color issues, it seem to only appear with the command substitution.

**Comment by saurabhdaware** [comment]
Colors are actually working fine for me (Linux (Ubuntu 18)).
If that is the case then can you use `inquirer.createPromptModule()` only in `getPath()` function and keep `inquirer.prompt()` for `openProject()` and other functions. 
It's fine if the colors are lost in `getPath` but `openProject` is kind of important function where I really care about colors

**Comment by ZakariaTalhami** [comment]
The colors only disappear when the command is used in $(), in other cases it works fine. I attached some examples:

**Using `pm path` normally:**
image

**Using `pm path` within $():**
image

**Using `pm open`:**
image

Note, these are tested in both *terminal* and *iTerm* on my macbook, i havent got around to testing it on Windows.

So the base functionality still is the same, and i dont see a reason to change `createPromtModule` to be just for `getPath`

**Comment by saurabhdaware** [comment]
Oh cool then, Would you mind solving conflicts with develop branch?

**Pull request merged**
