### PR TITLE
Custom editor management

### PR DESCRIPTION
**Pull request by fechy**
Added 2 useful things:
- addEditor => To add any editor you use
- project default editor => You'll be asked to select your editor when creating a new project.

### CODE REVIEW

**Comment by fechy** [comment]
I didn't cover the case when `settings.editors[]` is not in the `settings.json` already. Should be easy to fix.

What I'm trying to accomplish is to have a more flexible manager:
1) I have projects I use `webstorm`, and projects I use `Rider`, others `VSCode`, etc. and it is a bit annoying to having to change the editor before opening the project. Therefore being able to select the editor per project is very useful.

2) Adding new editors in the CLI is also more convenient, and being able to save it in the `settings.json` is definitely preferable than editing JS or, as in point 1, having to switch the editor per project.

**Comment by saurabhdaware** [comment]
I think that will make the codebase a little complicated (and I can't really afford it at a moment since the project is in its initial state) so I don't really think creating new value in settings and handling settings.editors is worth at a moment.

I actually thought of having something like `pm seteditor wstorm` which will set `wstorm` command and the `pm seteditor` command will just work as it is. It will be easier to add without changing any major thing in codebase.

Would you like to work on this? If yes, You can edit in the same code or close this PR and create new PR (which I'll highly recommend) it's up to you.

**Comment by saurabhdaware** [comment]
So here's what I finally think we can do,

let's just drop the idea of `pm seteditor-forproject <command>` and simply leave this to `pm edit`.
So if anyone wants to have separate commands to open projects they can set it inside projects array in settings.json with (and the default one would work as it is)
```json
 "projects": [
        {
            "name":"MyCoolProject",
            "path":"/home/path/projects/mycoolproject",
            "editor":"vim"
        },
        {
            "name":"TwoProject",
            "path":"/path/something/project"
        }
    ]
```

and all we'll have to do inside code is 
```js
const commandToOpen = project.editor || settings.commandToOpen;
```
**Reason**
Actually there are a lot of cases where you'll have to change `settings.json` (to sort the projects, to change the name of the project) so let's not just avoid the `pm edit` command. Also, since they will only have to do it once I don't think any user will mind doing it.

**Comment by saurabhdaware** [comment]
@fechy  Can you confirm if you are working on this? I would like to add this to `v1.1.0` which I am trying to release asap, so let me know if you are working on it :)

**Comment by saurabhdaware** [comment]
Resolved in fe481498a8ffaf70e967dc4cac8bf14e56a33a55, Thank you for your input 🌻

**Comment by fechy** [comment]
Hi @saurabhdaware sorry, I don't have the time right now to continue working on this.
Keep up the good work, I'll try to contribute as soon as I'm free again.
Cheers.

**Pull request closed without merging**
